-- SetSetting()

ExoY = ExoY or {}
ExoY.settings = ExoY.settings or {}

local Settings = ExoY.settings


function Settings.Apply()
  -- Gameplay Settings

  ---------------------
  -- Camera Settings --
  ---------------------
  SetSetting(SETTING_TYPE_CAMERA, CAMERA_SETTING_SMOOTHING, 1)
  SetSetting(SETTING_TYPE_CAMERA, CAMERA_SETTING_INVERT_Y, 0)
  SetSetting(SETTING_TYPE_CAMERA, CAMERA_SETTING_FOV_CHANGES_ALLOWED, 1) --QUESTION
  SetSetting(SETTING_TYPE_CAMERA, CAMERA_SETTING_ASSASSINATION_CAMERA, 0)
  SetSetting(SETTING_TYPE_CAMERA, CAMERA_SETTING_SCREEN_SHAKE, 0)
  -- First Person
  --SetSetting(SETTING_TYPE_CAMERA, CAMERA_SETTING_SENSITIVITY_FIRST_PERSON, )
  --SetSetting(SETTING_TYPE_CAMERA, CAMERA_SETTING_FIRST_PERSON_FIELD_OF_VIEW, )
  --SetSetting(SETTING_TYPE_CAMERA, CAMERA_SETTING_FIRST_PERSON_HEAD_BOB, )
  -- Third Person
  SetSetting(SETTING_TYPE_CAMERA, CAMERA_SETTING_SENSITIVITY_THIRD_PERSON, 1.16)
  SetSetting(SETTING_TYPE_CAMERA, CAMERA_SETTING_THIRD_PERSON_FIELD_OF_VIEW, 65)
  SetSetting(SETTING_TYPE_CAMERA, CAMERA_SETTING_THIRD_PERSON_HORIZONTAL_POSITION_MULTIPLIER, 0)
  SetSetting(SETTING_TYPE_CAMERA, CAMERA_SETTING_THIRD_PERSON_HORIZONTAL_OFFSET, 0) --TODO
  SetSetting(SETTING_TYPE_CAMERA, CAMERA_SETTING_THIRD_PERSON_VERTICAL_OFFSET, -0.25)
  SetSetting(SETTING_TYPE_CAMERA, CAMERA_SETTING_THIRD_PERSON_SIEGE_WEAPONRY, SIEGE_CAMERA_CHOICE_CONSTRAINED)

  -- Interface Settings
  -- Nameplates Settings
  -- Social Settings
  -- Combat Settings

end

--[[

https://github.com/esoui/esoui/tree/master/esoui/ingame/optionspanels

SettingSystemType
    SETTING_TYPE_ACCOUNT
    SETTING_TYPE_ACTION_BARS
    SETTING_TYPE_ACTIVE_COMBAT_TIP
    SETTING_TYPE_AUDIO
    SETTING_TYPE_BUFFS
    SETTING_TYPE_CAMERA
    SETTING_TYPE_CHAT_BUBBLE
    SETTING_TYPE_CHAT_GLOBALS
    SETTING_TYPE_CHAT_TABS
    SETTING_TYPE_COMBAT
    SETTING_TYPE_DEVELOPER_DEBUG
    SETTING_TYPE_GAMEPAD
    SETTING_TYPE_GRAPHICS
    SETTING_TYPE_IN_WORLD
    SETTING_TYPE_LANGUAGE
    SETTING_TYPE_LOOT
    SETTING_TYPE_NAMEPLATES
    SETTING_TYPE_SUBTITLES
    SETTING_TYPE_TUTORIAL
    SETTING_TYPE_UI
    SETTING_TYPE_VOICE




SettingSystemPanel
    SETTING_PANEL_ACCOUNT
    SETTING_PANEL_AUDIO
    SETTING_PANEL_CAMERA
    SETTING_PANEL_CINEMATIC
    SETTING_PANEL_COMBAT
    SETTING_PANEL_DEBUG
    SETTING_PANEL_GAMEPLAY
    SETTING_PANEL_INTERFACE
    SETTING_PANEL_NAMEPLATES
    SETTING_PANEL_SOCIAL
    SETTING_PANEL_VIDEO


]]

--SetSetting(SETTING_TYPE_GRAPHICS, GRAPHICS_SETTING_GAMMA_ADJUSTMENT, 100)
--SETTING_TYPE_GRAPHICS
--GRAPHICS_SETTING_GAMMA_ADJUSTMENT
